### ISSUE TITLE
Chisa, Butry-sur-Oise, Toussus-le-Noble: unknown successor

### ISSUE THREAD

**Issue by jdesboeufs** [etalab/geohisto#27]
Chisa has a successor which is not in the dataset. <del>Should be Corse splitting related.</del>

```bash
cat data/towns.csv | grep COM2B366@1976-01-01

COM20366@1947-04-12,20366,1947-04-12 00:00:00,1975-12-31 23:59:59,Chisa,COM2B366@1976-01-01,,DEP20@1860-07-01,NULL,410
```

A side-effect is an erroneous id for the second occurrence of Chisa.

```bash
cat data/towns.csv | grep Chisa

COM20366@1942-01-01,20366,1976-01-01 00:00:00,9999-12-31 23:59:59,Chisa,,,DEP20@1860-07-01,NULL,200
COM20366@1947-04-12,20366,1947-04-12 00:00:00,1975-12-31 23:59:59,Chisa,COM2B366@1976-01-01,,DEP20@1860-07-01,NULL,410
```

**Comment by jdesboeufs** [comment]
Original output was: `Record COM2B366@1976-01-01 not found`

**Comment by jdesboeufs** [comment]
Other cases:

```
Record COM2B366@1976-01-01 not found
Record COM95120@1968-01-01 not found
Record COM78620@1969-11-29 not found
```

**Comment by rhanka** [comment]
Ces cas ne sont bien que trois. L'impact est également que les successeurs des prédécesseurs de ces communes sont incomplets : Chisa / COM20366@1942-01-01 n'a pas COM2B366@1976-01-01 comme successeur alors que c'est bien la commune actuelle.
