### ISSUE TITLE
La région Centre-Val de Loire a changé de nom par la loi du 16 janvier 2015 

### ISSUE THREAD

**Issue by benoitdavidfr** [etalab/geohisto#57]
Avant la loi du 16 janvier 2015, la région s'appelait "Centre".
La loi a été publiée au JO du 17/1/2015. Je suppose donc qu'elle s'applique à compter du 18/1/2015.

## Detailed Description

décomposer en 2 objets se succédant

## Current result

fr:region:24@1970-01-09,24,1970-01-09 00:00:00,9999-12-31 23:59:59,Centre-Val de Loire,,,2570546,39151,FR24,fr:commune:45234@1942-01-01,https://fr.wikipedia.org/wiki/Centre-Val_de_Loire

## Correct result

fr:region:24@1970-01-09;24;1970-01-09 00:00:00;2015-01-17 23:59:59;Centre;fr:region:24@2015-01-18;;2570546;39151;FR24;fr:commune:45234@1942-01-01;https://fr.wikipedia.org/wiki/Centre-Val_de_Loire
fr:region:24@2015-01-18;24;2015-1-18 0:00:00;9999-12-31 23:59:59;Centre-Val de Loire;;fr:region:24@1970-01-09;2570546;39151;FR24;fr:commune:45234@1942-01-01;https://fr.wikipedia.org/wiki/Centre-Val_de_Loire

**Comment by davidbgk** [comment]
👍 Merci !

* https://www.legifrance.gouv.fr/jo_pdf.do?numJO=0&dateJO=20150117&numTexte=1&pageDebut=00777&pageFin=00783
* https://fr.wikipedia.org/wiki/Loi_relative_%C3%A0_la_d%C3%A9limitation_des_r%C3%A9gions,_aux_%C3%A9lections_r%C3%A9gionales_et_d%C3%A9partementales_et_modifiant_le_calendrier_%C3%A9lectoral
