### ISSUE TITLE
Arthieul case

### ISSUE THREAD

**Issue by davidbgk** [etalab/geohisto#8]
Current:

```
→ cat exports/towns/towns.csv | grep Arthieul            37ms
950251968-01-019999-01-01,95025,Arthieul,1968-01-01,9999-01-01,,780251942-01-011968-01-01,NULL,0
780251942-01-011968-01-01,78025,Arthieul,1942-01-01,1968-01-01,950251968-01-019999-01-01,,NULL,410
```

See http://www.insee.fr/fr/methodes/nomenclatures/cog/fichecommunale.asp?codedep=95&codecom=025

**Comment by davidbgk** [comment]
Probably the same case as Blamécourt http://www.insee.fr/fr/methodes/nomenclatures/cog/fichecommunale.asp?codedep=95&codecom=065

**Comment by jdesboeufs** [comment]
Updated output:

```bash
cat data/towns.csv | grep Arthieul
COM95025@1968-01-01,95025,1968-01-01 00:00:00,1968-01-01 00:00:00,Arthieul,COM78355@1942-01-01,COM78025@1942-01-01,DEP95@1968-01-01,NULL,310
COM78025@1942-01-01,78025,1942-01-01 00:00:00,1967-12-31 23:59:59,Arthieul,COM95025@1968-01-01,,DEP78@1860-07-01;DEP78@1968-01-01,NULL,410
```

I think the second entry should not have `DEP78@1968-01-01` as parent since its end datetime is before the departement start datetime.

**Comment by davidbgk** [comment]
Fixed in https://github.com/etalab/geohisto/commit/74302b7ed1564f9811109171122adc2a9e05ed38
